### PR TITLE
Do not list license if not needed

### PR DESCRIPTION
**Pull request by mickamy**
Some OSS licenses do not require notice.

See https://choosealicense.com/appendix/

### CODE REVIEW

**Comment by k-tomoyasu** [comment]
@mickamy Thanks for your pull request!  
I think it's better to be optional feature, because it could cover use case to show all licenses.

**Comment by mickamy** [comment]
@k-tomoyasu 
Added option `--skip-not-required`.

**Comment by k-tomoyasu** [comment]
Thanks for your quickly response:smiley:

**Comment by k-tomoyasu** [comment]
@mickamy published the new package as `0.3.0`. thanks!

**Pull request merged**
